### PR TITLE
feature: add test on Windows and MacOSX

### PR DESCRIPTION
**Pull request by YuriCat**
Jobs run in parallel.

### CODE REVIEW

**Comment by ikki407** [comment]
Thanks! It will be more stable. 

By the way, what do you think about running tests with multiple python versions? 3.6, 3.7, 3.8

ref. https://docs.github.com/en/actions/guides/building-and-testing-python#using-multiple-python-versions

**Comment by YuriCat** [comment]
> By the way, what do you think about running tests with multiple python versions? 3.6, 3.7, 3.8
> 
> ref. https://docs.github.com/en/actions/guides/building-and-testing-python#using-multiple-python-versions

This is what we needed!

**Comment by ikki407** [comment]
If the multiple version take a long time, using a cache of pip dependencies will be needed.

**Comment by YuriCat** [comment]
#166 is a better way.

**Pull request closed without merging**
