### PR TITLE
update: batch_first style for using nn.DataParallel

### PR DESCRIPTION
**Pull request by YuriCat**
Using batch_first style is good for multi-GPUs training of RNNs.

(when we use feedforward nets, it's OK to leave it as it is unless multi-gpu computation of loss function)

### CODE REVIEW

**Comment by ikki407** [comment]
I have checked the changes.

**Comment by YuriCat** [comment]
update: merged lastet master

**Comment by YuriCat** [comment]
In some experiments, this change seems to avoid long repetition in self-play games in Geister.
Some more verification would be needed.

**Comment by ikki407** [comment]
thank you for the verification!

**Pull request merged**
