### PR TITLE
feature: add losses plot and stats plot

### PR DESCRIPTION
**Pull request by ikki407**
loss_plot

### CODE REVIEW

**Comment by YuriCat** [comment]
Great feature!

In my laptop and TicTacToe environment, this error frequently occurs.
Is it not good that the current HandyRL outputs one extra line of losses when Ctrl+C?

```
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (90,) and (91,)
```

**Comment by YuriCat** [comment]
Since current `develop` branch doesn't output average step, this line dumps error.
Do we need `step` output?
``` 
steps = float(elms[8]), float(elms[10])
IndexError: list index out of range
```

**Comment by ikki407** [comment]
Thank you for your check and so sorry for your inconvenience. I will reconsider it with HandyRL’s outputs. I couldn’t take Carl-C into account. 

I think `step` info is very informative in most games :)

**Comment by ikki407** [comment]
The loss plot script is updated and the stats plot script is deleted.
I checked this script with #307 and it worked even with server-mode and disconnect.

loss_plot_server_mode_disconnect

**Comment by ikki407** [comment]
I checked `Ctrl+C` interruption version of logs and it worked.

```
epoch 7
win rate = 0.522 (46.5 / 89)
generation stats = 0.000 +- 0.909
loss = p:-0.016 v:0.113 ent:1.600 total:-0.013
updated model(22)
2100 ^CProcess Process-3:6:
```

**Pull request merged**
